### ISSUE TITLE
Commit to private repo without authorization

### ISSUE THREAD

**Issue by georoot** [Djacket/djacket#2]
Hi, a person can commit to a private repo without having the proper credentials to the account.

**Comment by moeenz** [comment]
Hi
What credentials can be used to access a private repo?

**Comment by georoot** [comment]
I tried with django super user account to commit to private repo of a normal user. Also is this still under dev ? would love to help u if i can

**Comment by moeenz** [comment]
When I test this exact scenario, the superuser can't access a private repo.

Yes, Djacket is under development and in version 0.1, unfortunately I didn't have time to update it in the last months, and I would very much appreciate your contribution to this project.
